name: publish

permissions:
  contents: read

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy to ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: VS Marketplace
            registryUrl: https://marketplace.visualstudio.com
          - name: Open VSX
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - run: corepack enable && pnpm install --frozen-lockfile

      - name: Publish to VS Marketplace
        if: ${{ matrix.name == 'VS Marketplace' && secrets.VS_MARKETPLACE_TOKEN != '' }}
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com

      - name: Publish to Open VSX
        if: ${{ matrix.name == 'Open VSX' && secrets.OPEN_VSX_TOKEN != '' }}
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
